"""user table changed: added image file field

Revision ID: 123453f8fdd4
Revises: a57f494826ae
Create Date: 2020-07-24 08:29:49.356623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '123453f8fdd4'
down_revision = 'a57f494826ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_file', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image_file')
    # ### end Alembic commands ###
